services:
  development:
    build: .
    volumes:
      - ./reports:/opt/perftest/reports
    depends_on:
      service:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
    environment:
      S3_ENDPOINT: 'http://localstack:4566'
      RESULTS_OUTPUT_S3_PATH: 's3://test-results'
      ENVIRONMENT: local
      SERVICE_ENDPOINT: service
      SERVICE_PORT: 5555
      SERVICE_URL_SCHEME: http
    networks:
      - performance-tests

  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    restart: always
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN
      SERVICES: s3, sqs, sns
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: [ "CMD", "stat", "/tmp/READY" ]
      interval: 3s
      start_period: 5s
      retries: 3
    networks:
      - performance-tests

  redis:
    image: redis:7.2.3-alpine3.18
    restart: always
    networks:
      - performance-tests

  postgres:
    image: postgres:16.6
    env_file:
      - 'compose/postgres.env'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cads_data_service}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d cads_data_service']
      interval: 3s
      start_period: 5s
      retries: 5
    networks:
      - performance-tests

  service:
    image: defradigital/cads-data-service:${SERVICE_VERSION:-latest}
    ports:
      - '5555:5555'
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - 'compose/aws.env'
      - 'compose/postgres.env'
      - 'compose/cads-service.env'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5555/health']
      interval: 5s
      start_period: 30s
      retries: 10
    networks:
      - performance-tests

networks:
  performance-tests:
    driver: bridge
